blog/urls.py
from blog.apps import BlogConfig
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from blog.views import (
    BlogPostListView,
    BlogPostCreateView,
    BlogPostDetailView,
    BlogPostUpdateView,
    BlogPostDeleteView,
)
from catalog.views import ContactListView

app_name = BlogConfig.name

urlpatterns = [
    path("contact/", ContactListView.as_view(), name="contact"),
    path("", BlogPostListView.as_view(), name="blog_list"),
    path("blog/<int:pk>/", BlogPostDetailView.as_view(), name="blog_detail"),
    path("blog/create/", BlogPostCreateView.as_view(), name="blog_create"),
    path("blog/<int:pk>/update/", BlogPostUpdateView.as_view(), name="blog_update"),
    path("blog/<int:pk>/delete/", BlogPostDeleteView.as_view(), name="blog_delete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import (
    ProductListView,
    ProductDetailView,
    ContactListView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
)

app_name = CatalogConfig.name

urlpatterns = [
    path("contacts/", ContactListView.as_view(), name="contacts"),
    path("", ProductListView.as_view(), name="product_list"),
    path("product/<int:pk>/", ProductDetailView.as_view(), name="product_detail"),
    path("product/create/", ProductCreateView.as_view(), name="product_create"),
    path(
        "product/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"
    ),
    path(
        "product/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
]

blog/models.py
from django.db import models


class BlogPost(models.Model):
    title = models.CharField(
        max_length=20, verbose_name="Название блога", help_text="Введите название блога"
    )
    content_blog = models.TextField(
        blank=True, null=True, verbose_name="Содержимое", help_text="введите содержимое"
    )
    photo = models.ImageField(
        upload_to="photo",
        blank=True,
        null=True,
        verbose_name="Изображение",
        help_text="Загрузите изображение для блога",
    )
    date_publication = models.DateField(
        blank=True,
        null=True,
        verbose_name="Дата публикации",
        help_text="Дата публикации",
    )
    bool_blog = models.BooleanField(default=False, verbose_name="Статус публикации")
    view_cointer = models.PositiveIntegerField(
        verbose_name="Счетчик просмотров",
        help_text="Укажите количество просмотров",
        default=0,
    )

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"

    def __str__(self):
        return self.title

catalog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(
        max_length=50, verbose_name="Название", help_text="Введите название категории"
    )
    description = models.TextField(
        blank=True,
        null=True,
        verbose_name="Описание категории",
        help_text="Введите описание категории",
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["name"]

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name="Название продукта",
        help_text="Введите название продукта",
    )
    description = models.TextField(
        blank=True,
        null=True,
        verbose_name="Описание продукта",
        help_text="Введите описание продукта",
    )
    photo = models.ImageField(
        upload_to="photo",
        blank=True,
        null=True,
        verbose_name="Фото продукта",
        help_text="Загрузите фото продукта",
    )
    category = models.ForeignKey(
        Category, on_delete=models.DO_NOTHING, related_name="products"
    )
    purchase_price = models.IntegerField(
        verbose_name="Цена за покупку продукта",
        help_text="Укажите цену за покупку продукта",
    )
    created_at = models.DateField(
        blank=True,
        null=True,
        verbose_name="Дата создания продукта",
        help_text="Укажите дату создания продукта",
    )
    updated_at = models.DateField(
        blank=True,
        null=True,
        verbose_name="Дата изменения продукта",
        help_text="Укажите дату изменения продукта",
    )

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["created_at", "updated_at", "name", "category", "purchase_price"]

    def __str__(self):
        return self.name

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from .models import BlogPost


class BlogPostListView(ListView):
    model = BlogPost


class BlogPostDetailView(DetailView):
    model = BlogPost

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_cointer += 1
        self.object.save()
        return self.object


class BlogPostCreateView(CreateView):
    model = BlogPost
    fields = ("title", "content_blog", "photo", "date_publication")
    success_url = reverse_lazy("blog:blog_list")


class BlogPostUpdateView(UpdateView):
    model = BlogPost
    fields = ("title", "content_blog", "photo", "date_publication", "bool_blog")
    success_url = reverse_lazy("blog:blog_list")

    def get_success_url(self):
        return reverse("blog:blog_detail", args=[self.kwargs.get("pk")])


class BlogPostDeleteView(DeleteView):
    model = BlogPost
    success_url = reverse_lazy("blog:blog_list")

catalog/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    TemplateView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import Product


class ProductListView(ListView):
    model = Product


class ProductDetailView(DetailView):
    model = Product


class ContactListView(TemplateView):
    template_name = "catalog/contacts.html"


class ProductCreateView(CreateView):
    model = Product
    fields = (
        "name",
        "description",
        "photo",
        "category",
        "purchase_price",
        "created_at",
    )
    success_url = reverse_lazy("catalog:product_list")


class ProductUpdateView(UpdateView):
    model = Product
    fields = (
        "name",
        "description",
        "photo",
        "category",
        "purchase_price",
        "created_at",
        "updated_at",
    )
    success_url = reverse_lazy("catalog:product_list")


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("catalog:product_list")

blog/templates/blog/blogpost_confirm_delete.html
{% extends 'catalog/home.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Действительно хотите удалить? {{ object.name }}</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-primary">Удалить</button>
                    <a role="button" href="{% url 'blog:blog_list' %}" class="btn btn-primary">Отменить</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends 'catalog/home.html' %}

{% load my_tags %}
{% block content %}

<div class="container">
    <div class="row text-center">
        <div class="col-2"></div>
        <div class="col-8">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h3 class="my-0 font-weight-normal">{{ object.title }}</h3>
                </div>
                <div class="card-body">
                    <img src="{{ object.photo | media_filter }}" style="max-height: 200px; width: 100%; object-fit: cover;">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ object.content_blog }}</li>

                        <li>Дата выпуска: {{ object.date_publication }}</li>
                        <li>Статус {{ object.bool_blog }}</li>

                    </ul>
                    <a role="button" href="{% url 'blog:blog_update' object.pk %}" class="btn btn-primary">Редактировать</a>
                    <a role="button" href="{% url 'blog:blog_list' %}" class="btn btn-primary">Назад</a>
                </div>
            </div>
        </div>
        <div class="col-2"></div>
    </div>
{% endblock %}

blog/templates/blog/blogpost_form.html
{% extends 'catalog/home.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">
                    {% if object %}
                    Обновить
                    {% else %}
                    Добавить
                    {% endif %}
                </button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blogpost_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
{% include 'catalog/includes/inc_menu_up.html' %}

{% load my_tags %}
{% block content %}

<div class="container">
    <div class="row text-center">
        {% for blog in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ blog.title }}</h4>
                </div>
                <div class="card-body">
                    <img src="{{ blog.photo | media_filter }}" style="max-height: 200px; width: 100%; object-fit: cover;">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    </ul>
                    <li> Кратко: {{ blog.content_blog | default:"Блог отсутствует" | truncatechars:50 }} </li>
                    <a role="button" href="{% url 'blog:blog_detail' blog.pk %}" class="btn btn-primary">Посмотреть</a>
                    <a role="button" href="{% url 'blog:blog_update' blog.pk %}" class="btn btn-primary">Редактировать</a>
                    <a role="button" href="{% url 'blog:blog_delete' blog.pk %}" class="btn btn-primary">Удалить</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}


{% include 'catalog/includes/inc_menu_down.html' %}


</body>
</html>

catalog/templates/catalog/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
{% include 'catalog/includes/inc_menu_up.html' %}


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% include 'catalog/includes/inc_menu_down.html' %}
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/home.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

</head>
<body>
{% include 'catalog/includes/inc_menu_up.html' %}

{% block content %}
{% endblock %}

{% include 'catalog/includes/inc_menu_down.html' %}

</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/includes/inc_menu_down.html
 <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>

catalog/templates/catalog/includes/inc_menu_up.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/blog">Блог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_create' %}">Добавить продукт</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:blog_create' %}">Добавить Блог</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/home.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Действительно хотите удалить? {{ object.name }}</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-primary">Удалить</button>
                    <a role="button" href="{% url 'catalog:product_list' %}" class="btn btn-primary">Отменить</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}

<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <h2 class="card-title pricing-card-title">{{ object.purchase_price }}руб.</h2>
                    <img src="{{ product.photo | media_filter }}" style="max-height: 200px; width: 100%; object-fit: cover;">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Описание: {{ object.description | default:"Описание отсутствует" | truncatechars:100  }}</li>
                        <li>Дата выпуска: {{ object.created_at }}</li>
                        <li>Категория: {{ object.category }}</li>
                    </ul>
                    <a role="button" class="btn btn-primary">Купить</a>
                    <a role="button" href=" {% url 'catalog:product_list' %}" class="btn btn-primary">Назад</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/home.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">
                    {% if object %}
                    Обновить
                    {% else %}
                    Добавить
                    {% endif %}
                </button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/home.html' %}
{% load my_tags %}
{% block content %}

<div class="container">
    <div class="row text-center">
        {% for product in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                </div>
                <div class="card-body">
                    <h2 class="card-title pricing-card-title">{{ product.purchase_price }}руб.</h2>
                    <img src="{{ product.photo | media_filter }}" style="max-height: 200px; width: 100%; object-fit: cover;">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Описание: {{ product.description | default:"Описание отсутствует" | truncatechars:100  }}</li>
                    </ul>
                    <a role="button" href="{% url 'catalog:product_detail' product.pk %}" class="btn btn-primary">Посмотреть</a>
                    <a role="button" href="{% url 'catalog:product_update' product.pk %}" class="btn btn-primary">Редактировать</a>
                    <a role="button" href="{% url 'catalog:product_delete' product.pk %}" class="btn btn-primary">Удалить</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
{% include 'includes/inc_menu_up.html' %}


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% include 'includes/inc_menu_down.html' %}
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/includes/inc_menu_up.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

catalog/templates/product_detail.html
{% extends 'home.html' %}
{% load my_tags %}
{% block content %}

<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                </div>
                <div class="card-body">
                    <h2 class="card-title pricing-card-title">{{ product.purchase_price }}руб.</h2>
                    <img src="{{ product.photo | media_filter }}" style="max-height: 200px; width: 100%; object-fit: cover;">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Описание: {{ product.description | default:"Описание отсутствует" | truncatechars:100  }}</li>
                        <li>Дата выпуска: {{ product.created_at }}</li>
                        <li>Категория: {{ product.category }}</li>
                    </ul>
                    <a role="button" class="btn btn-primary">Купить</a>
                    <a role="button" href=" {% url 'catalog:product_list' %}" class="btn btn-primary">Назад</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}